on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner specification
        type: string
        required: false
        default: ubuntu-latest
      java-version:
        description: Java version
        type: string
        required: false
        default: "11"
      java-distribution:
        description: Java distribution
        type: string
        required: false
        default: zulu
      java-architecture:
        description: Java architecture
        type: string
        required: false
        default: x64
      code-signing-private-key-fingerprint-env-variable:
        description: Name of the environment variable containing code signing GPG private key fingerprint
        type: string
        required: false
        default: CODE_SIGNING_KEY_FINGERPRINT
      code-signing-private-key-passphrase-env-variable:
        description: Name of the environment variable containing code signing GPG private key passphrase
        type: string
        required: false
        default: CODE_SIGNING_KEY_PASSPHRASE
      deployment-server-id:
        description: Server id of the artifact deployment repository
        type: string
        required: false
      deployment-server-username-env-variable:
        description: Name of the environment variable containing the deployment repository username
        type: string
        required: false
        default: DEPLOYMENT_SERVER_USERNAME
      deployment-server-password-env-variable:
        description: Name of the environment variable containing the deployment repository password
        type: string
        required: false
        default: DEPLOYMENT_SERVER_PASSWORD
      upload-coverage:
        description: Upload code coverage reports to Codecov.IO
        type: boolean
        required: false
        default: false
      profiles:
        description: Comma separated list of profiles to activate
        type: string
        required: false
        default: ""
      version:
        description: The version to release
        type: string
        required: true
      revision-incrementor:
        description: The revision incrementing strategy
        type: string
        required: false
        default: auto
      sha1:
        description: The maven ci-friendly sha1 property to use
        type: string
        required: false
        default: ""
      changelist:
        description: The maven ci-friendly changelist property to use
        type: string
        required: false
        default: ""
      git-user-name:
        description: The git user name
        type: string
        required: false
        default: Automaton
      git-user-email:
        description: The git user email
        type: string
        required: false
        default: bot@bestquality.engineering
      release-branch:
        description: The name of the release branch to create
        type: string
        required: false
        default: release/{0}
      base-branch:
        description: The branch into which the release branch will be merged
        type: string
        required: false
        default: main
    secrets:
      code-signing-private-key:
        description: Code signing GPG private key
        required: false
      code-signing-private-key-passphrase:
        description: Code signing GPG private key passphrase
        required: false
      code-signing-private-key-fingerprint:
        description: Code signing GPG private key fingerprint
        required: false
      deployment-server-username:
        description: Deployment server username
        required: false
      deployment-server-password:
        description: Deployment server password
        required: false
env:
  ${{inputs.code-signing-private-key-fingerprint-env-variable}}: ${{secrets.code-signing-private-key-fingerprint}}
  ${{inputs.code-signing-private-key-passphrase-env-variable}}: ${{secrets.code-signing-private-key-passphrase}}
  ${{inputs.deployment-server-username-env-variable}}: ${{secrets.deployment-server-username}}
  ${{inputs.deployment-server-password-env-variable}}: ${{secrets.deployment-server-password}}
  CI_MAVEN_RELEASE_BRANCH: ${{format(inputs.release-branch, inputs.version)}}
jobs:
  deploy-release:
    runs-on: [ "${{inputs.runs-on}}" ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Runtime Environment
        uses: Best-Quality-Engineering/ci-maven-actions/setup-runtime@v1
        with:
          java-version: ${{inputs.java-version}}
          java-distribution: ${{inputs.java-distribution}}
          java-architecture: ${{inputs.java-architecture}}
          code-signing-private-key: ${{secrets.code-signing-private-key}}
          code-signing-private-key-passphrase-env-variable: ${{inputs.code-signing-private-key-passphrase-env-variable}}
          deployment-server-id: ${{inputs.deployment-server-id}}
          deployment-server-username-env-variable: ${{inputs.deployment-server-username-env-variable}}
          deployment-server-password-env-variable: ${{inputs.deployment-server-password-env-variable}}
      - name: Export Revision
        id: export-revision
        uses: Best-Quality-Engineering/ci-maven-actions/export-revision@v1
        with:
          version: ${{inputs.version}}
      - name: Deploy Release Artifacts
        uses: Best-Quality-Engineering/ci-maven-actions/deploy-release@v1
        with:
          profiles: ${{inputs.profiles}}
          revision: ${{steps.export-revision.outputs.revision}}
          sha1: ${{inputs.sha1}}
          changelist: ${{inputs.changelist}}
      - name: Upload Code Coverage
        if: ${{inputs.upload-coverage}}
        uses: codecov/codecov-action@v3
      - name: Configure Git User
        uses: Best-Quality-Engineering/ci-maven-actions/git-user@v1
        with:
          name: ${{inputs.git-user-name}}
          email: ${{inputs.git-user-email}}
      - name: Create Release Branch
        uses: Best-Quality-Engineering/ci-maven-actions/create-branch@v1
        with:
          name: ${{env.CI_MAVEN_RELEASE_BRANCH}}
      - name: Increment Project Revision
        uses: Best-Quality-Engineering/ci-maven-actions/increment-pom@v1
        with:
          profiles: ${{inputs.profiles}}
          incrementor: ${{inputs.revision-incrementor}}
          revision: ${{steps.export-revision.outputs.revision}}
          sha1: ${{inputs.sha1}}
      - name: Update Version References in Documentation
        uses: Best-Quality-Engineering/ci-maven-actions/replace-content@v1
        with:
          profiles: ${{inputs.profiles}}
          revision: ${{steps.export-revision.outputs.revision}}
          sha1: ${{inputs.sha1}}
          changelist: ${{inputs.changelist}}
      - name: Merge Release Branch
        uses: Best-Quality-Engineering/ci-maven-actions/merge-release-branch@v1
        with:
          version: ${{inputs.version}}
          release-branch: ${{env.CI_MAVEN_RELEASE_BRANCH}}
          base-branch: ${{inputs.base-branch}}
